### ISSUE TITLE
how about next and previous button in player??

### ISSUE THREAD

**Issue by ghimireprashant** [VeinGuo/VGPlayer#1]
can you add custom view option in the player view(ie like to add ads)and also next and previous button

**Comment by VeinGuo** [comment]
ok,I will be added to the example.

**Comment by ghimireprashant** [comment]
thank you @VeinGuo .

**Comment by ghimireprashant** [comment]
is it possible to make it display in half screen mode (i.e inline mode)??

**Comment by VeinGuo** [comment]
Thank you for your suggestions.In the plan, the next version will be supported.
 I will tell you in this issues.

**Comment by ghimireprashant** [comment]
thank you mate
