### ISSUE TITLE
embed in cell of tableView

### ISSUE THREAD

**Issue by hdehghan** [VeinGuo/VGPlayer#10]
when embeded in cell of tableView, after entering fullscreen and exit from fullscreen, the player don't add to cell and imbeded in main screen.

**Comment by VeinGuo** [comment]
@hdehghan   These days I will write a embeded in cell of tableView example.  I'll @ you when I'm done.

**Comment by VeinGuo** [comment]
@hdehghan  Hi you can download the latest code, see Example  `Embed in cell of tableView`.
