### ISSUE TITLE
Add back Button to ads View

### ISSUE THREAD

**Issue by rehannali** [VeinGuo/VGPlayer#11]
Hey, I'm trying to add another button in top corner right end so it can also be used for the back button. I tried to insert it and add constraints but the button is not showing up. I attached changing in your code so you know what I changed or what I need to do to work it.
Thanks

<img width="630" alt="screen shot 2017-08-03 at 5 02 37 pm" src="https://user-images.githubusercontent.com/22426977/28921003-acdca0de-786d-11e7-94dc-6fff7fcbff39.png">
<img width="350" alt="screen shot 2017-08-03 at 5 02 57 pm" src="https://user-images.githubusercontent.com/22426977/28921004-acdd024a-786d-11e7-8fe1-34ef9c38ce9d.png">
<img width="672" alt="screen shot 2017-08-03 at 5 03 05 pm" src="https://user-images.githubusercontent.com/22426977/28921005-ad122b82-786d-11e7-8c30-8f836470a5c4.png">

**Comment by rehannali** [comment]
I also tried constant with -20 and -30 but it didn't work.

**Comment by VeinGuo** [comment]
@rehannali  Hi,  I read your code probably because `backButton.isHidden = true`, so the button not show.

**Comment by rehannali** [comment]
@VeinGuo Thanks, It helps.
