### ISSUE TITLE
Watermark on video player or video

### ISSUE THREAD

**Issue by rehannali** [VeinGuo/VGPlayer#12]
Hey, I want a watermark on left bottom side on player or video. Is there any possibility so I can add watermark on left bottom side on the player?

**Comment by VeinGuo** [comment]
@rehannali Hello, i can think of the way is to add UIImageView to Watermark on the view.

**Comment by rehannali** [comment]
Could you please help me to add UIImageView on player view. You understand your code well and firstly, I've to understand it by myself to add it. If you could guide me where I can add it, it would be very appreciated.

**Comment by VeinGuo** [comment]
@rehannali  like this.
![image](https://user-images.githubusercontent.com/14232017/29109458-a97db598-7d15-11e7-9185-4a7c5f9cadc8.png)
Code in `configurationUI ()`
![image](https://user-images.githubusercontent.com/14232017/29109480-b99b104c-7d15-11e7-8115-41576e9b89ad.png)

**Comment by rehannali** [comment]
Okay, Now I understand. Thanks for the help.
