### ISSUE TITLE
video play

### ISSUE THREAD

**Issue by arvincong** [VeinGuo/VGPlayer#13]
sometimes this video has no sound ,but drag the progress ，the sound has again.

**Comment by VeinGuo** [comment]
@arvincong Hi, can you provide a test video link? I am easy to debug this problem.

**Comment by arvincong** [comment]
thanks.  this video link  https://www.svsmix.com/upload/20170703/1499073407455.mp4 ,ios9.0，repeat play many times ，this question will appear .

**Comment by VeinGuo** [comment]
@arvincong   Because I did not iOS 9 iPhone, so debugging with iOS 9 simulator did not appear what you said.

**Comment by arvincong** [comment]
VGPlayer Log -------------------------- 
 error: Optional(Error Domain=NSURLErrorDomain Code=-1 "unknown error" UserInfo={NSLocalizedDescription=unknown error, NSUnderlyingError=0x608000248d60 {Error Domain=NSOSStatusErrorDomain Code=-12935 "(null)"}})
 playerItemErrorLogEvent: nil
 extendedLogData: nil
 extendedLogDataStringEncoding nil
 -------------------------   second play ，it is ok . this why

**Comment by VeinGuo** [comment]
@arvincong This error, may be related to the URL format, such as the wrong format: https: //w.svsmix.com/upload/20170703/1499073407455.mp4  
Maybe you can provide test link, I try debugging again.   <(~︶~)>

**Comment by arvincong** [comment]
player.pause can not pause ，stop a while ,it is still play .  this why

**Comment by kennybuc** [comment]
Play/pause button is really not working. When I choose to pause the video, it automatically resume again.... !!!!

**Comment by kennybuc** [comment]
@VeinGuo I have got another video link and it's also not playing at all. The sample link in your Embed table view controller is really working fine. But when I use my personal video link, it's not playing at all in table view.

**Comment by VeinGuo** [comment]
@arvincong  @kennybuc  pause error  fix  42b8ea9

**Comment by VeinGuo** [comment]
@kennybuc  Hi,  Can you send me your test address, I'm debugging.

**Comment by kennybuc** [comment]
@VeinGuo I'm sorry, but I can't provide you the link because it's private video which online users purchase to look. I can just tell you that it's a vimeo file link. With Vimeo pro account, we have an option to get file links of the video uploaded to vimeo. Please let me know if you have anything confused.

**Comment by kennybuc** [comment]
@VeinGuo Another question! How can I get your code update on VGPlayer.swift?
I did pod update, but it didn't check out your latest commit.

**Comment by kennybuc** [comment]
@VeinGuo Okay, here is the url which causes an issue.
https://player.vimeo.com/external/228514333.sd.mp4?s=83191e2990d1b963a9e603b646a9bea7fcdf17f8&profile_id=164
When I open the link in browser, it's just working fine. It's also working in Android app with another player. Let me know if there is any news.

And I'm very happy to use your library. It's a very good library.

**Comment by kennybuc** [comment]
@VeinGuo Did you get any chance to make your player working with my vimeo video link?

**Comment by VeinGuo** [comment]
@kennybuc  I'm debugging this question. I found url param praser error, I was trying to fix this problem.  Give me some time i'll fix it.

**Comment by VeinGuo** [comment]
@kennybuc  This bug is because the URL with parameters, where the URL parsing error.
![image](https://user-images.githubusercontent.com/14232017/30091500-79d4ea22-92ec-11e7-8c7f-336acc8beeb6.png)

**Comment by VeinGuo** [comment]
@kennybuc  I fix this bug c3685d7, you can pod update. VGPlayer v0.1.5.

**Comment by kennybuc** [comment]
@VeinGuo Okay, it works. I have updated and it's working. Wow!!!
How could I recommend you and your library to others? This is great... haha

**Comment by VeinGuo** [comment]
@kennybuc Thanks for your.

**Comment by VishuWagh** [comment]
when the user changes the play rate from 1.0x to 1.5x etc.., of the video and it will not work properly in pause() and playing().

**Case 1**
when the video is on pause() state and the user changes the rate it will change and the video starts playing but pause() button image will not be changed.

**Case 2** 
when the video is in playing state and the user changes the rate it will change but the video does not play properly as per rate.

please check it and update me I'm stuck here for last 2 days.
Please help me!!! thanks in advance.

**Comment by roopmindz** [comment]
i am getting problem in swift 4, when i slide to end, video still playing. it shows current time and total time equal bu still video is playing can any one help me.
