### ISSUE TITLE
Disable certain pan gestures

### ISSUE THREAD

**Issue by mittenimraum** [VeinGuo/VGPlayer#15]
It would be nice to have the possibility to control whether you want the user to change the volume and brightness of the screen with a pan gesture or not.

**Comment by VeinGuo** [comment]
@mittenimraum  Hi, thank you for your suggestion, the next version I will add.

**Comment by VeinGuo** [comment]
`panGesture ` UIPanGestureRecognizer  control sound and brightness.

**Comment by mrhaxic** [comment]
Hello, is there any update on this?
