### ISSUE TITLE
Cache manager

### ISSUE THREAD

**Issue by kennybuc** [VeinGuo/VGPlayer#18]
@VeinGuo I'm going to implement offline video feature in app. I found that the library VGPlayer caches the video automatically. So here are some questions about video caching in this library.

1.  Is there any way to find the cache file path for the specific url in VGPlayer?
2.  Is there any option to enable/disable caching for the video in the library?
3.  I'm going to give the user an option to download the video. To make this logic compatible with your cache manager, I think it's good to download the video directly to the cache directory. Does your cache manager simply saves the video after download is completed? What happens if user close the app before the cache manager completes downloading?
4.  I'm looking for the solution to manually download the specific video file to the cache rather than cache manager automatically does. Is it possible?

It would be helpful for me if you explain about how your cache manager is working.
Any response is appreciated.

Thanks!

**Comment by VeinGuo** [comment]
Hi,thanks for using my project
1.  `VGPlayerCacheManager.cacheFilePath(for: url)`  can get to the video cache file path.
2.  Can not close the automatic cache, the next version I will add Bool parameters to set.
3.  The cache consists of two files, the video file and the cache progress file to save the video file to download the segment progress size, and if the user opens the application while downloading the application, the application is played again from the breakpoint.

![image](https://user-images.githubusercontent.com/14232017/30407696-5c30dee0-992c-11e7-8ec2-aaebff034a16.png)

![image](https://user-images.githubusercontent.com/14232017/30407706-6ccc1dc8-992c-11e7-9913-cf81ddeb001e.png)
The picture is from [VIMediaCache](https://github.com/vitoziv/VIMediaCache)

The cache is implemented by `AVAssetResourceLoaderDelegate`, which is cached.
[AVAssetResourceLoaderDelegate](https://developer.apple.com/documentation/avfoundation/avassetresourceloaderdelegate)

**Comment by kennybuc** [comment]
@VeinGuo So I want to know what happens when I manually download the video file to the cache file path?
For example, I'm going to add download button which downloads the video from url to the cache file path. I'm wondering if this can cause an issue to your library while your library may try to download the video the the same path at the same time while playing.
Can you please let me know?

Thanks!

**Comment by VeinGuo** [comment]
@kennybuc  If the manual download, download directly after the completion of the local file, VGPlayer will not do the cache.

**Comment by kennybuc** [comment]
@VeinGuo Thanks for explanation and support. I appreciate!
