### ISSUE TITLE
Paste board doesn't work.

### ISSUE THREAD

**Issue by PCGurjar** [VeinGuo/VGPlayer#20]
I am using "PHFComposeBarView" a third party liberary in my chat app, but after integrating this in my app. my compose bar doesn't responding paste options. Only compose bar didn't works fine but in other screens in textview or textfield paste board working.
Please suggest me how would I fix this.

**Comment by VeinGuo** [comment]
Do not know why, maybe you can stackoverflow.

**Comment by PCGurjar** [comment]
I didnt get any clue over there
