### ISSUE TITLE
hittest extension issue

### ISSUE THREAD

**Issue by PCGurjar** [VeinGuo/VGPlayer#21]
what is the specific use of hit test in uibutton extension. in VGPlayer classes. Because it creates some issue in my project can i remove this extension.  and video not playing automatically in ios9 or lower versions.

**Comment by VeinGuo** [comment]
@PCGurjar Hi, I am sorry to be a little busy recently. This extension is just https://stackoverflow.com/questions/808503/uibutton-making-the-hit-area-larger-than-the-default-hit-area/13977921

You can get rid of it. If it does cause a problem, I will remove the extension in the next version.
