### ISSUE TITLE
Changing timeout value for VGPlayer

### ISSUE THREAD

**Issue by tolgatanriverdi** [VeinGuo/VGPlayer#22]
Hi
We are using VGPlayer in our application but some of our users constantly report they cannot see the video.
When we investigate their log files it seems that VGPlayer says **"request timed out"**
We also encountered the same problem, while we have poor internet connection.

But we couldnt find where to change the timeout parameter.
Can you point us to the right direction?
Thanks

**Comment by VeinGuo** [comment]
@tolgatanriverdi Will you use the version after v0.1.5? Previous versions of some video URL resolution will appear this problem.

**Comment by tolgatanriverdi** [comment]
Thanks @VeinGuo  I'll give it a try

**Comment by tolgatanriverdi** [comment]
@VeinGuo I've updated the vgplayer to 0.2.0 version(was 0.1.5 before), but this time it updated snapkit to 4.0.0 and there was compiler errors while building it , related with snapkit.
So I needed to revert back to 0.1.5 (which is using 3.2.0 version of snapkit) and then I can succesfully build and run my app. But this doesnt solve my original **timeout** problem.
What do you suggest for us?

**Comment by VeinGuo** [comment]
@tolgatanriverdi  Can you provide a test video link?

**Comment by tolgatanriverdi** [comment]
Here is a link that you can test. (But it has 5 minutes time limit)

https://storage.googleapis.com/kidokit-dev-bucket/activity-videos/SampleVideo_1280x720_20mb-2017-09-09-213152545.mp4?GoogleAccessId=google-cloud-storage-service@kidokit-dev.iam.gserviceaccount.com&Expires=1506341626072&Signature=4c7%2FM2nBM1ofGqw7%2BeKi0CEhFAKAOAWYCV541I07V72zcc%2F2gyxxjx8pVRpuN761eNEp6fRp7VSS6or3FEFTraaW1qGaoz0c%2B%2F1AA2dy4Z7baN6sORJmthZaI9hJC0HOWKMpaYRuisMFf%2FbCsmQ%2Blt77Eai2i0uPXwSoU%2BXOiX%2FebidwBqa5VqLGdL10itn68KswNqx4DJntrE0Hvha1CfVPch%2B%2BtvfCfn0mwu8ZZutbp5FPhNA9x6bswwQDSlR4p%2BsyuZD1xMfoTVeQ4kjPe99UvWxMCBL4fQNFUEwsH1yvwiIXgS1HFeGZmFFBfDvw4%2BXRl7iXZibUtC79B2R0oQ%3D%3D

**Comment by VeinGuo** [comment]
@tolgatanriverdi  Sorry, I can't debug the problem. I play this link very smoothly.

![image](https://user-images.githubusercontent.com/14232017/30808582-4c37e5e8-a231-11e7-8ed9-a5356d2ca26a.png)
