### ISSUE TITLE
how to hide status top bar view?

### ISSUE THREAD

**Issue by meanreaksmey** [VeinGuo/VGPlayer#23]

**Comment by VeinGuo** [comment]
@meanreaksmey You mean the topView of PlayerView? By default, there is no hiding, you can customize the view, and then delete or hide it.
Or the default directly remove example:  `player.displayView.topView.removeFromSuperview()`

**Comment by meanreaksmey** [comment]
thanks you now it work.

**Comment by VeinGuo** [comment]
@meanreaksmey You can set the gesture directly to enable = false.
