### ISSUE TITLE
What kind of URL to play?

### ISSUE THREAD

**Issue by heuism** [VeinGuo/VGPlayer#24]
Hi VeinGuo, Thanks for this wonderful library. I just wonder what kind of url i can pass into the view? cause i tried the one in dropbox and seems like it is not working, So i am unsure what happen if i get from Azure storage for example. Would that still be ok? I am still new to this stuffs so i am not too sure what to ask. If my words are not really understandable, i will explain more.

**Comment by VeinGuo** [comment]
@heuism  Hi,I guess the dropbox link should be forbidden. For example: https: // quirtersmode.org/html5/videos/big_buck_bunny.mp4 can play.

**Comment by heuism** [comment]
@VeinGuo: Can I ask how to play the video you recorded by yourself? I tried using the path to the file, but not sure why it doesn't work. Thanks

**Comment by VeinGuo** [comment]
@heuism Hi ,You can look at the issue, I explained the realization of the cache. #18
