### ISSUE TITLE
[Bug] - UI + performance

### ISSUE THREAD

**Issue by Th3M4sk8712** [VeinGuo/VGPlayer#27]
I used your lib in my project and it has some bugs:
- When lock orientation from control center, I select "Fullscreen" -> player full screen normal -> select not fullscreen -> layout player is not correct. This bug appear
- Time duration and total duration are not correct when time duration is larger than 60 minutes.
- Performance: When streaming video, memory usage keeps increasing, not reduce, or less when change video, or dismiss. I test on iPad mini 3, RAM 1G, app will crash because of out of memory, about 45 min - 60m watching.
   Please check above issues :) I beleave you can fix them quickly and VGPlayer will be a perfect library.

**Comment by VeinGuo** [comment]
fix Time duration 041361c
