### ISSUE TITLE
Disk cache and memory cache

### ISSUE THREAD

**Issue by kennybuc** [VeinGuo/VGPlayer#29]
@VeinGuo 

Hello, I'm writing here in order to let you know that I'm experiencing some problems with video playing in iOS 9. (iOS 9.3.5 actually)
When I choose to play, it just shows black screen. No spinning circle. When I select play button, nothing happens.
In debug window, I found the following logcat. Not sure if it was from this library.

    Communications error: <OS_xpc_error: <error: 0x1075c7b40> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x1075c7ef0> { length = 22, contents = "Connection interrupted" }
}>

And sometimes the video has started but stopped in the middle. For example, it stopped at 00:11. It's supposed to show spinning circle if it's buffering but it doesn't show.
The issue happened on my iPad which has installed iOS 9.3.5. I've tried on iOS 9.3 simulator and found the same issue. It happens barely on simulator than iPad.

So there are two issues
- Video does not start at all with black screen
- Video started but stops in the middle.

I'm wondering if this is related with cache. Here are some questions.

- What is the difference between following methods?
VGPlayerCacheManager.shared.cleanAllCache()
VGPlayerCacheManager.shared.cleanOldFiles
I'm sorry for this question but I don't have got deep understanding about cache management in iOS. I guess these methods are related with memory cache and disk cache but I don't know exactly.

If video playing issue is related with cache management, what should I do to properly manage caches?

I appreciate your patience for reading my report. Please let me know if you have got some explanations.

Thanks!

**Comment by VeinGuo** [comment]
`VGPlayerCacheManager.shared.cleanAllCache()` Clear all caches.
`VGPlayerCacheManager.shared.cleanOldFiles` Clears the cache that exceeds the set cache time

**Comment by kennybuc** [comment]
@VeinGuo Do you have got any idea about why the video is not playing in iOS 9?

**Comment by VeinGuo** [comment]
@kennybuc Sorry, I use iOS9simulator debugging and did not find this problem. Hope you find this situation when giving me more information.
maybe you can solve, can pull requests, 
thanks.
