### ISSUE TITLE
Media Caching

### ISSUE THREAD

**Issue by waltermvp** [VeinGuo/VGPlayer#3]
I see that media caching might be on the roadmap. I'm curious what approach you might have in mind, as I might be able to contribute with a pull request.

**Comment by VeinGuo** [comment]
I want to use AVAssetResourceLoaderDelegate to caching
https://developer.apple.com/documentation/avfoundation/avassetresourceloaderdelegate

**Comment by VeinGuo** [comment]
@waltermvp  hi ，VGPlayer has support for Media Caching at 0.0.1.
