### ISSUE TITLE
xcode 10

### ISSUE THREAD

**Issue by NotLovelyChild** [VeinGuo/VGPlayer#61]
请尽快支持 xcode 10 
![image](https://user-images.githubusercontent.com/29365942/45662168-5cd52980-bb33-11e8-9ef9-3398eca2f5c3.png)

**Comment by asifbilal786** [comment]
I am also facing this issue.

**Comment by mrhaxic** [comment]
Just replace class func line with the below

`class func vgPlayer_scheduledTimerWithTimeInterval(_ timeInterval: TimeInterval, block: @escaping ()->(), repeats: Bool) -> Timer {`

**Comment by MZC0829** [comment]
can you convert to swift4.2? Thanks

**Comment by VeinGuo** [comment]
Fix 511c98c update swift 4.2 Xcode10 build
