### ISSUE TITLE
Video Format Support

### ISSUE THREAD

**Issue by rehannali** [VeinGuo/VGPlayer#7]
Which of formats are now available for streaming or play locally i.e. mov, mpeg etc?
I saw your demo it is outstanding but i only see link with mp4 files.

**Comment by VeinGuo** [comment]
Examples include .m3u8 and .mp4, but did not join .mov and .m4v, before the test I used the following link test to play
[m4v test link](http://media.vimcasts.org/videos/1/show_invisibles.m4v)
[mov test link](http://images.apple.com/media/cn/ipad/2011/tours/apple-ipad2-feature-cn-20110328_848x480.mov)
