### ISSUE TITLE
Issue: There is no sound some times 

### ISSUE THREAD

**Issue by kristoff2016** [VeinGuo/VGPlayer#73]
Hello thank you so much for nice plugin. 
There is small issue on sound when videos is playing no sound. 

It would be great it it will be fixed. I am going to upload my app soon. I can not wait 
But it would be great if you can help fix this issue 

thank you

**Comment by duyhungtnn** [comment]
hi @kristoff2016 , Have you found a solution for this issues ?

**Comment by kristoff2016** [comment]
Hi, I did not use this library anymore. unstable!
