### ISSUE TITLE
Error in originalURL

### ISSUE THREAD

**Issue by rehannali** [VeinGuo/VGPlayer#8]
I always get an error in originalURL "fatal error: unexpectedly found nil while unwrapping an Optional value" I debug code many times. I pass URL value to replaceVideo function but it didn't play my video. application crashes and gives me an error that I mentioned previously. 
I attached screenshot so you can understand my problem better and give me appropriate solution.
<img width="844" alt="screen shot 2017-07-15 at 9 10 32 pm" src="https://user-images.githubusercontent.com/22426977/28240842-126d4488-69a2-11e7-9785-865ae6d848b7.png">

**Comment by VeinGuo** [comment]
@rehannali  Hi I suspect that the crash is caused by URL parsing
Maybe you can provide your test URL?

**Comment by rehannali** [comment]
Actually, all URLs came as JSON through API so I don't exactly know which one of them causing an issue but I give you some URLs.
These are some URLs...
http://reflektions.world/files/Minions%20%28short%20film%29.mp4
http://reflektions.world/files/AWARD%20WINNING%20Best%20Short%20Video%20-%20Share.%20Care.%20Joy.%20-%20By%20Naik%20Foundation.mp4

**Comment by VeinGuo** [comment]
@rehannali  Hey my judgment right. Is indeed a crash caused by URL encoding.  
fixed: 0f420b4    
Fix after the above two test links are no problem, before the crash. 
Thank you  man.

**Comment by rehannali** [comment]
So now I need to update Pod to get all the changes?

**Comment by VeinGuo** [comment]
@rehannali  yes, I updated the pod at 0.1.3 to fix this problem

**Comment by rehannali** [comment]
@VeinGuo Thanks for help to resolve my issue.

**Comment by rehannali** [comment]
@VeinGuo I've problem with fullscreen. I almost use same code as example and changed where i needed but full screen is not working. Could you please tell me what cause this problem?

**Comment by rehannali** [comment]
I debug code related to full screen and there is some problem, the player isn't changing its location. It stays portrait. I add a player to the upper most hierarchy but I didn't know exact problem what should I do to solve this problem so player changes its state.

**Comment by VeinGuo** [comment]
I am running example in iOS10 and iOS 11 full screen can work.
Do not know why your full screen can not work, maybe you can paste some of the full-screen key code you write, so I can better know the cause of the problem.

**Comment by rehannali** [comment]
Actually, I didn't write one. I'm using your code with some modifications.

**Comment by rehannali** [comment]
I attached some screenshots to identify the problem. This is code which I've changed from example custom 2. You see playerview initialization. This class is same as ads custom class.
<img width="762" alt="screen shot 2017-07-16 at 6 50 54 pm" src="https://user-images.githubusercontent.com/22426977/28248095-c3562d22-6a57-11e7-86dc-eb6d75924ea5.png">
<img width="454" alt="screen shot 2017-07-16 at 6 51 12 pm" src="https://user-images.githubusercontent.com/22426977/28248096-c35992fa-6a57-11e7-85fe-56fd8f0a299b.png">

**Comment by VeinGuo** [comment]
@rehannali  Hi as you set in the picture.
![image](https://user-images.githubusercontent.com/14232017/28273507-27d084e8-6b41-11e7-9444-31730bad578c.png)

You can look at these two questions, may be able to solve your problem.
https://stackoverflow.com/questions/25651969/setting-device-orientation-in-swift-ios
https://stackoverflow.com/questions/26357162/how-to-force-view-controller-orientation-in-ios-8/28220616#28220616

**Comment by rehannali** [comment]
I use now all settings you asked and as you use in your example project but still the same problem. I tried every thing but still, i can't resolve the full-screen problem even I override orientation function.

**Comment by rehannali** [comment]
@VeinGuo I tried all solutions but now i can rotate screen but video enlarge at portrait mode. It is not going in landscape mode. Any solutions?

**Comment by rehannali** [comment]
@VeinGuo My bad, there is a problem in AppDelegate. Thanks for the assistance. I know the problem and it should remove all conflicts and now code working fine.
